name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  plugin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nightly Rust Toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: aarch64-skyline-switch

      - name: Install cargo-skyline
        run: cargo install cargo-skyline

      - name: Build release NRO
        run: cargo skyline build --release

      - name: Upload plugin artifact
        uses: actions/upload-artifact@v4
        with:
          name: plugin
          path: target/aarch64-skyline-switch/release/*.nro
